# Note: derived from: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/ai-ml/gke-ray/rayserve/llm/

apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llm-model-serve
spec:
  serveConfigV2: |
    - name: llm
      route_prefix: /
      import_path:  luna-llm-serve.llm:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 8
          # NOTE: num_gpus is set automatically based on TENSOR_PARALLELISM
      runtime_env:
        working_dir: "https://github.com/elotl/skyray/archive/main.zip"
        pip: ["vllm==0.4.3"]
        env_vars:
          MODEL_ID: mosaicml/mpt-7b-chat
          TENSOR_PARALLELISM: 1
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        metadata:
          labels:
            elotl-luna: "true"
        spec:
          containers:
          - name: ray-head
            image: anyscale/ray-ml:2.32.0
            resources:
              limits:
                cpu: "2"
                memory: "8Gi"
              requests:
                cpu: "2"
                memory: "8Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 0
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        metadata:
          labels:
            elotl-luna: "true"
          annotations:
            node.elotl.co/instance-gpu-skus: "L4,A10G,A10,L40S"
        spec:
          containers:
          - name: llm
            image: anyscale/ray-ml:2.32.0
            resources:
              limits:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: "1"
