apiVersion: ray.io/v1
kind: RayService
metadata:
  name: ray-serve-llm
  labels:
    app.kubernetes.io/instance: rayservice
spec:
  serveConfigV2: |
    applications:
    - name: llms
      import_path: ray.serve.llm:build_openai_app
      route_prefix: "/"
      args:
        llm_configs:
        - model_loading_config:
            model_id: microsoft/Phi-3-mini-4k-instruct
          engine_kwargs:
            dtype: bfloat16
          deployment_config:
            autoscaling_config:
              min_replicas: 2
              max_replicas: 4
  rayClusterConfig:
    rayVersion: "2.46.0"
    headServiceAnnotations:
      service.cilium.io/global: "true"
    ## raycluster autoscaling config
    enableInTreeAutoscaling: true
    autoscalerOptions:
      upscalingMode: Default
      resources:
        limits:
          cpu: "1"
          memory: "1000Mi"
        requests:
          cpu: "1"
          memory: "1000Mi"
    headGroupSpec:
      serviceType: NodePort
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: "0"
        num-gpus: "0"
      template:
        metadata:
          labels:
            elotl-luna: "true"
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray-llm:2.46.0-py311-cu124
            resources:
              limits:
                cpu: "2"
                memory: "8Gi"
              requests:
                cpu: "2"
                memory: "8Gi"
            ports:
            - containerPort: 6379
              name: gcs
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            - containerPort: 8000
              name: serve
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
    workerGroupSpecs:
    - replicas: 0
      minReplicas: 0
      maxReplicas: 4
      numOfHosts: 1
      groupName: gpu-group
      rayStartParams:
        num-gpus: "1"
      template:
        metadata:
          labels:
            elotl-luna: "true"
          annotations:
            node.elotl.co/instance-gpu-skus: "L4,A10G,A10,L40S"
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray-llm:2.46.0-py311-cu124
            resources:
              limits:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: "1"
          tolerations:
            - key: nvidia.com/gpu
              effect: NoSchedule
              operator: Exists
