apiVersion: ray.io/v1
kind: RayService
metadata:
  name: text-summarizer
  labels:
    app.kubernetes.io/instance: rayservice
spec:
  serveConfigV2: |
    applications:
      - name: text_summarizer
        import_path: text_summarizer.text_summarizer:deployment
        runtime_env:
          working_dir: "https://github.com/ray-project/serve_config_examples/archive/refs/heads/master.zip"
        deployments:
          - name: SummaryDeployment
            num_replicas: 2
            max_replicas_per_node: 1
            ray_actor_options: {num_gpus: 0, num_cpus: 4}
  rayClusterConfig:
    rayVersion: '2.9.0' # Should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      # Pod template
      template:
        metadata:
          labels:
            elotl-luna: "true"
          annotations:
            node.elotl.co/instance-offerings: "on-demand"
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.9.0
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
            resources:
              limits:
                cpu: "2"
                memory: "8G"
              requests:
                cpu: "2"
                memory: "8G"
          volumes:
            - name: ray-logs
              emptyDir: {}
    workerGroupSpecs:
    # The pod replicas in this group typed worker
    - replicas: 2
      minReplicas: 1
      maxReplicas: 10
      groupName: cpu-group
      rayStartParams: {}
      # Pod template
      template:
        metadata:
          labels:
            elotl-luna: "true"
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray-ml:2.9.0
            resources:
              limits:
                cpu: 4
                memory: "16G"
              requests:
                cpu: 4
                memory: "16G"
