apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: crd-policy
spec:
  spreadConstraints:
    spreadMode: Duplicate
    topologyKey: kubernetes.io/metadata.name
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/component: ${APP_COMPONENT_NAME}
  groupBy:
    labelKey: app.kubernetes.io/component
