apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: kr-policy
spec:
  spreadConstraints:
    spreadMode: Duplicate
    topologyKey: kubernetes.io/metadata.name
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/name: ${K8S_APP_NAME}
  groupBy:
    labelKey: app.kubernetes.io/name
