apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: cache-policy-${APP_NAMESPACE}
spec:
  spreadConstraints:
    spreadMode: Duplicate
    topologyKey: kubernetes.io/metadata.name
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/instance: nimcache
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  groupBy:
    labelKey: app.kubernetes.io/instance
