apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: raycluster-policy
spec:
  clusterSelector:
    matchLabels:
      nova.elotl.co/cluster.region: "us-west-2"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/instance: raycluster
