apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: rayservice-policy-${RAYCLUSTER_NAMESPACE}
spec:
  orderedClusterSelector:
    matchExpressions:
      - key: nova.elotl.co/cluster.provider
        operator: In
        values:
          - openstack
          - gce
          - aws
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: ${RAYCLUSTER_NAMESPACE}
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/instance: rayservice
  groupBy:
    labelKey: app.kubernetes.io/instance
