apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: rayservice-spread-upgrade-policy-${RAYCLUSTER_NAMESPACE}
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: ${RAYCLUSTER_NAMESPACE}
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app.kubernetes.io/instance: rayservice
  groupBy:
    labelKey: app.kubernetes.io/instance
